blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/mariovagomarzal/cookiecutter-dotfiles/discussions
    about: Have a question or need help? Ask it here!
